project:
  type: website
  resources:
    - Stat5100.Rmd
  render:
    - "*.qmd"
    - "!Stats5100.Rmd"


website:
  title: "Jesse Wheeler"
  navbar:
    left:
      # - href: index.qmd
      #   text: Home
      - href: texDocs/cv.pdf
        text: CV
      - text: Professional Statements
        menu:
          - text: Research Statement
            href: texDocs/researchStatement.pdf
          - text: Teaching Statement
            href: texDocs/teachingStatement.pdf
          - text: Diversity Statement
            href: texDocs/DEIstatement.pdf
      - text: Software
        menu:
          - text: panelPomp (R)
            href: https://panelpomp-org.github.io
          - text: pypomp (Python)
            href: https://github.com/pypomp
          - text: arima2 (R)
            href: https://github.com/jeswheel/arima2
      - text: Courses
        menu:
          - text: Math 4450 (F25)
            href: https://jeswheel.github.io/4450_f25
          - text: Math 3350 (F25)
            href: https://jeswheel.github.io/3350_f25
      # - about.qmd

format:
  html:
    theme:
      dark: darkly
      light: united
    css: styles.css
    toc: true



