project:
  type: website

website:
  title: "Jesse Wheeler"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: texDocs/cv.pdf
        text: CV
      - href: texDocs/researchStatement.pdf
        text: Research Statement
      # - about.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



