project:
  type: website
  resources:
    - Stat5100.Rmd
  render:
    - "*.qmd"
    - "!Stats5100.Rmd"


website:
  title: "Jesse Wheeler"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: texDocs/cv.pdf
        text: CV
      - href: texDocs/researchStatement.pdf
        text: Research Statement
      - href: texDocs/teachingStatement.pdf
        text: Teaching Statement
      - href: texDocs/DEIstatement.pdf
        text: Diversity Statement
      - href: https://panelpomp-org.github.io
        text: PanelPomp
      # - about.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    css: styles.css
    toc: true



